### ISSUE TITLE
Grant program

### ISSUE THREAD

**Issue by tromer** [ZcashFoundation/ZcashFoundation#2]
The Zcash Foundation can fund projects done by Zcash community members, by awarding specific grants.

It would work like this:
* The Foundation issues a Call for Proposals listing the topics of interest and application procedures. 
* People submit Grant Proposals, explaining their ideas for proposed projects, deliverables, schedule and budget &mdash; aiming to show that the ideas are worthwhile for the Zcash community, and that the proposers can execute them.
* The Foundation chooses which of these to fund, and executes a funding arrangement.
* The award winners do perform their projects, and report on their achievements.

There are many degrees of freedom:
1. Scope of activities: development? online resources? communications? science?
_(suggested: all, guided by the Foundation's [mission](https://github.com/ZcashFoundation/ZcashFoundation/blob/master/MISSION.md) and [values](https://github.com/ZcashFoundation/ZcashFoundation/blob/master/VALUES.md))_
2. Type and magnitude of expenses?
_(suggested: 1-6 person months of effort, budgeted below typical salaries but not embarrassingly so; direct expenses such as servers fully covered)_
3. Payment method (ZEC or USD? tax implications and procedures?)
_(suggested: ZEC, and seek tax accountant advice)_
4. Payment timing and conditions (upfront? upon completion? by milestone? receipts needed for expenses?)
_(suggested: keep it simple, with upfront payment that is formally unconditional; but keep project size commensurate to applicants' reputation and qualification)_
5. Application schedule: ongoing, deadlines, periodic?
_(suggested: announce deadlines, adaptively but ideally every ~6 months, to allow batched consideration and to allow for focused PR on this funding opportunity)_
6. Are proposals public, all except budget numbers, or not at all? When proposed, or once accepted?
_(suggested: accepted proposals should be fully published; not sure about proposed ones)_
7. Who decides?
_(suggested: a panel appointed by the Foundation board. If proposals are published (see above), set up a forum for public discussion.)_
8. Reserved budget?
_(suggested: in each CFP cycle, the Foundation will reserve enough budget for at least one project of the maximum size deemed within scope, e.g., ~6 person months)_
9. What to requite as report/deliverables?
_(suggested: winners commit to publishing a final report, shortly after the scheduled projecty end time, which briefly describe the achievements and point to deliverables such code and online services. This is for the sake of transparency, ease of locating products , and evaluating future proposals from the same proposers. But not technically linked to the payment, which would remain upfront.)_

(The above summarizes a [discussion on the community chat](https://chat.zcashcommunity.com/channel/zcash-foundation?msg=XAKwXpqLb9hmxuxJT).)

**Comment by radix42** [comment]
Here're my thoughts.....

1. yes of course "all of the above"

2. that seems right, depending on ones subjective view of what those numbers are! and would of course vary wildly by where the grantee lives, etc.

3. ZEC is so much simpler and is what the Foundation is funded in, and tax implications are going to vary so wildly by the legal jurisdiction of the grantee's residence that I'd just go with paying in ZEC and they can convert/spend that however is best for them

4. I'm 100% on board with your proposed answer to this one, too. Making it conditional on hitting milestones or completion would make things much more subjective and possibly contentious

5.  this answer also sounds good....dunno if quarterly may or may not be better than every 6 months

6. I'd make accepted ones public for both transparency and PR purposes, but keep non-accepted ones private to prevent idea sniping and ego bruising issues

7.  your suggestion here sounds very good, too

8. this is good too, depending of course on what level of expenses the Foundation ends up incurring otherwise. this'll probably take some tweaking along the way no matter what number or % is chosen, of course

9.  this sounds like the right thing, too

**Comment by amiller** [comment]
Two more thoughts. Both are along the lines of radical transparency. While I imagine this will be done by board-appointed-committee at first, I'd like to start a path towards more inclusive deliberation.
- On #6, let's make it so that proposers can choose to make their proposals public or not? If public, they can self host, and we'd timestamp with archive.org or something. We'd also guarantee that proposers get back a review of some kind, which we'd optionally publish, if the authors want. 
- For public submissions, we should incorporate some form of input, e.g. provide at least some funding for the most upvoted post (as usual, the question would become, how do we count, without being gamed?) We could start by having the panel at least acknowledge the community input.

**Comment by tromer** [comment]
What's a good place to accumulate ideas/suggestions for grant-funded projects?

For example, I'd like to suggest implementing some version of https://github.com/zcash/zcash/issues/2432 .

**Comment by jackgavigan** [comment]
> On #6, let's make it so that proposers can choose to make their proposals public or not?

👎 to this. I think a precondition of any grant should be that the proposal must be made public (even if it is private during the application stage). 

Note that keeping applications private during the application phase makes it difficult to assess community support for a proposal. One way of sidestepping this problem is to only make grants on a matching basis - i.e. the Foundation will only fund a portion of the cost, and will only release the funds when donations for the remainder have been received. 

This approach also helps prevent astroturfing. 

Relevant suggestion from the Forums: https://forum.z.cash/t/june-16-2017-dev-update/17308/6

**Comment by asm13243546** [comment]
@jackgavigan A note in passing that ideas [6] are sure to be actively mined by vc-blockchain startups and there may be some incentive to participants for tiering participant privacy? 

Or is ZCF simply exemplary. Feel you on astroturfing.

**Comment by asm13243546** [comment]
Maybe it's simply an IP question writ small. Software licensing, you'e in or you're out.

**Comment by tromer** [comment]
Following a discussion with @amiller, @jackgavigan and others, and subsequent tweaking, I suggest the following plan:

All proposals will be public, with the intention of fostering public review, transparency, and drawing on the knowledge and skills of the wide Zcash community to evaluate and hone proposals.

Final funding decisions will be made by a _Zcash Grant Panel_, to be chosen/approved by the Zcash Foundation board.

The proposal process:
1. The proposer files a Github issue (in a dedicated repo that the Foundation will set up), explaining the tentative proposal, informally but in detail. This must be done by a _Filing Deadline_, ~5 weeks after the _Call for Proposals_.
2. Public discussion will ensue in comments on the filed issue. The discussion will hopefully include support, critique, suggestions for improvements and pointers to relevant resources.
3. No later than the _Submission Deadline_, ~3 weeks after the Filing Deadline: the proposer will draft a formal stand-alone _Submission_ document that summarizes their official proposal (structure TBD), and post it as an attachment in the issue. The Submission may be revised by filing new ones within the issue (e.g., to address ongoing feedback), until the Submission Deadline.

After the Submission Deadline, the Zcash Grant Panel will convene to make its funding decision, based on the submissions and the community feedback gathered in the issues.

Comments, in particular about the transparency and timeline?

**Comment by amiller** [comment]
Here is a wiki page where people we can collect ideas for projects that would make good grant proposals:
https://github.com/ZcashFoundation/ZcashFoundation/wiki/Grant-Project-Ideas

**Comment by nathan-at-least** [comment]
Is this ticket worthy to be closed, given the success of the first Grant Program round?
