### ISSUE TITLE
Scholarship Program

### ISSUE THREAD

**Issue by nathan-at-least** [ZcashFoundation/ZcashFoundation#3]
I wonder if the Foundation could award scholarship funding for students or researchers involved in target areas of research. A small-scoped case might be in providing funding to attend conferences.

I'm not sure how distinct this is from a grant program, and maybe this would just be a particular case of grants, if this is feasible.

**Comment by radix42** [comment]
I have mentioned funding for conference attendance on the chat. Including the fact that I wouldn't be able to go to Zcon0 without support for that from somewhere.

**Comment by bradycoye** [comment]
Cool idea! I think an update to Solar Designers [Equihash analysis](openwall.com/articles/Zcash-Equihash-Analysis) with current network metrics and potential risk would be a valuable research topic.

**Comment by acityinohio** [comment]
Closing this out since we're done with the first grant program, but I think this should be a contender for the next one! (Also @radix42 though we're in early stages on planning Zcon0, I believe there will be opportunities for the Zcash Foundation to support scholarships for attending the conference, but stay tuned there)
