### ISSUE TITLE
Polling Miners

### ISSUE THREAD

**Issue by amiller** [ZcashFoundation/ZcashFoundation#4]
I'd like to build a system to poll miners. "System" is intentionally vague here. It could be technical in nature, such as encouraging a convention of including "miner input" data in some memo field or coinbase space in a block. It could also include social conventions. 
One obvious way to poll miners is to interact with the large mining pools. Another option is to engage mining pools and actively encourage/support them to provide means of polling their individual members.

**Comment by mineZcash** [comment]
There are a number of options we can use to deploy a voting system. 

The first step will be to decide _who_ exactly we want to invite to the poll, as you mentioned the Pool operators are an obvious choice since they have so many miners working for them. I know that Zooko and other team members have direct contact information for some the major Pool operators and I know some of their usernames on the Chat, we can begin by (privately) compiling a list and send invites explaining the intentions to make their voices heard.

The next step to is to set up a poll with a verification system. I have found several websites and Github Projects that offer polling but not all are free and I'm not sure how/if they support a voter registration process, (I can do more research into that once we find one we like) 

Web Based Options: (most cost $$)
https://framadate.org/
https://www.typeform.com/
https://www.surveyhero.com/
https://www.surveymonkey.com/

Github Options:
https://github.com/collective/collective.polls
https://github.com/LimeSurvey/LimeSurvey
https://github.com/mckinseyacademy/xblock-poll

Once we have an polling solution running for ourselves we can offer it to the pool operators to use with their members too.

**Comment by amiller** [comment]
This is awesome, thanks for working out this list of alternatives.

I guess the way to start is with invite-only polling? 

Eventually this seems like something for which an actual technical solution might be a good idea. Miners may wish to vote anonymously rather than have their names attached. The public may be skeptical that the polling system is not transparent enough, the registration process is too biased, etc. Maybe we should start with something really bad to begin with, and use it as a way of figuring out what we care most about improving. 

I'd like to think through also what the procedure is for submitting things to be voted on. Id like to see this made somewhat frequently, not so often that it's annoying, but often enough that it's normal not exceptional. Maybe we could do something like use the forum to generate questions and crudely upvote them, and ask mining pools to check every month? Is that more annoying than helpful? What do we envision some initial questions would be?

**Comment by acityinohio** [comment]
Closing this as part of ZcF GitHub Issues cleanup.
