### ISSUE TITLE
Governance and Board of Directors election

### ISSUE THREAD

**Issue by amiller** [ZcashFoundation/ZcashFoundation#56]
We should have a Board of Directors election for the Zcash Foundation, and improve/broaden our decision making process. We should time this so that the details are finalized over the next few months, and the election itself is commemorated at the Zcon0 event (which will tentatively be held in June some time). 

The following is a barebones, minimum viable, strawman proposal for how this election could work:

 **_1. We should make an assignment of “voting weight”_** to represent the voices of different groups / interests within the Zcash community. 

  Just to be concrete about things, here's an initial proposal:

- 0.20 Donors to the Zcash Foundation
- 0.20 Miners (proportional by hashpower)
- 0.20 Current Zcash holders (proportional to value)
- 0.20 Board-chosen allocation of outside experts / “friends of the foundation”
- 0.20 Board-chosen allocation of contributors / developers

For each of these, there is at least some apparent path to take towards measuring and soliciting input them (though the devil is in the details).

Our plan should be to conduct this process in the most pragmatic ways possible, making creative use of technology and/or foundation staff effort as necessary. (E.g., we could collect signed reports from mining pools about their hashpower and how its distributed.)

We should also feature a common-sense approach to delegative democracy. You should definitely be able to delegate your vote to someone else. This shouldn't have to be complicated.

 **_2. Election of a larger board, with more representation of groups within the community._**
  I'd suggest we do the following, which seems like a graceful compromise of status quo and gradual growth:
- One new board seat, to be elected by each of the five interests/groups identified above. This makes a total of 10 board seats. 
- The 5 bootstrap board members may choose to either gracefully depart, or run for “confirmation” from the voters as weighted above.

 **_3. Ratification of any bylaws / processes for the next year_**
   
 **_4. Finally, ratify and publicly deliberate as many “resolutions” as we have time/energy for_** 
  I have an idea a list of “tough questions” for the community to discuss.

Any thoughts on this plan?

**Comment by acityinohio** [comment]
Great start! I'm very much in favor with the general intent of the proposal; it's a good idea to add more process to the board and expanding bylaws with community buy-in.

Based on the discussion we had in the [Zcash community chat](https://chat.zcashcommunity.com/channel/the-zcash-foundation?msg=KPj8XEjJzhvbJHyM3) I agree getting some of these changes done before Zcon would be ideal (so we can report there), though I'd prefer a more iterative approach.

In line with that thinking, a few pieces of feedback on the strawman proposal:

- No qualms with **points 3 and 4**; that should be the end goal.
- On **points 1 and 2**: Agree that the board should be larger, but not sure 10 is the ideal number; best to have an odd number to break deadlock scenarios.
- Smaller groups are generally better for decision-making (and even for more mundane administrata, like achieving quorum for decisions and organizing meetings) but they also run the risk of not collecting enough feedback from stakeholders. A good min-max principle here: let's minimize the number of board members necessary to maximize exposure to stakeholder interests.
- In line with that principle I'd suggest some changes to the voting weights you describe, with the goal of having **7 board seats filled** prior to the new bylaw/resolution process:
- Remove the last two "Board-chosen" allocations; based on the current bylaws, the board will already have power to veto/allow the new board appointments, and they can provide feedback/influence when they decide to leave.
- That leaves the last three weights; of these, I'd prioritize Zcash holders first, then donors, then finally miners (who already have influence based on hashpower...they might be the first group to poll when an existing board member vacates).

Thoughts on this @amiller / @ebfull /others?

**Comment by diracdeltas** [comment]
> One new board seat, to be elected by each of the five interests/groups identified above. This makes a total of 10 board seats.

This would mean that 2 out of the 5 new seats (assuming the vote weight distribution above) are strongly influenced by the existing board members, via their allocations of outside experts / foundation friends / contributors / developers. To me this feels like too much power in the hands of the existing board. Maybe "board-chosen allocation of contributors / developers" could be replaced with "set of people who have contributed to the source code" (either all of them or some subset chosen by the project maintainers), or some other way of determining contributors that isn't board-dependent.

Additional TODO item: Pre-election, I think the board needs to write up some criteria for who is eligible to run for a board position to avoid accidentally electing members who have a conflict of interest.

**Comment by ebfull** [comment]
> To me this feels like too much power in the hands of the existing board.

I see a danger in the organization moving "too quick" in some direction. In the worst case the organization can be "hijacked" by influence that then acts to entrench itself. In a less-worse case a lot of institutional knowledge, principles, values and experience can be lost. (Also, when the board composition is subject to significant sudden change it could potentially disincentivize action.)

I personally think there needs to be a natural "churn rate" where the current board members are gradually replaced by new board members according to some fitness function, i.e., a multi-stakeholder election process that is continually adjusted by the board as the ecosystem changes.

My opinion is:

* a small board (7 sounds good)
* board members should resign (or be removed) in a gradual process over time
* their replacements should be decided by an election that weighs particular stakeholders of the community in a way that the board members think is beneficial for the organization and the community

All of these decisions don't need to be made at once. As an example, we can decide on a "good enough" weighted representation of the community and begin electing new board members, and then adjust the process as we go. Then, the board can decide on a "good enough" number of board members. Then, the board can further rebalance the community representation as board members resign (or are forced to, by process).

I'm just not sure how the process of stimulating churn should work. Should we set something in stone, like seniority or term limits? Should it be a tradition to resign after some time? Should the community vote to replace a board member whenever it votes to add one?

**Comment by zookozcash** [comment]
Here's the kind of decision that I think the Zcash community as a whole should be able to make eventually (within the next couple of years): Resolved: that the block reward shall be changed to go 50% to the miner and 50% to a variety of developers from now on until the next such change.

Whether it is possible to make such decisions and how it would be done is the stuff of the Constitutional Convention.

This is pretty high-stakes. At the moment the Zcash block reward is worth about $150,000,000 per month! That's about $1.7bn per year.

Since it is high stakes this means there will be strong pressure to "capture" or "corrupt" the process in order to drive that money toward your interests. I put scare-quotes there because I'm not sure there is an objective, bright-line difference between "capture/corruption" and well-intentioned engagement with the governance process in order to drive some of the money toward socially beneficial outcomes. It seems to me that an implicit goal of Andrew's design is just to make sure that multiple *different* stakeholders are "capturing/positively-contributing-to" the process. Sounds like a good idea to me.

In specific, I'd advocate for simplicity of the structure, since it can grow and evolve in incremental steps on the future. Since you've identified five classes of stakeholder, why not just have a 5-person board and a process intended to give control of one seat to each class?

I like what Sean suggested about incremental evolution of the board. Maybe each year a different seat is up for change, so 5 years per seat. Maybe there is a limit of one or two terms per person.

**Comment by zookozcash** [comment]
The Constitutional Convention doesn't have to provide an answer to all questions — especially future policies (e.g. should The Zcash Foundation spend all of its money in 2018 or save up!?) — but it should I think answer two things:

1. Who is going to have power over The Zcash Foundation and how can that change? I think Andrew's original post here is targeted at that and it is perfect.

2. What is sacred? What strongly held values do we all share? For example, a lot of people I'll bet think that having a fixed ZEC total eventual supply limit (e.g. 21 million coins) is sacred. For me it's not! I just chose to copy it from Bitcoin in order to have something people were familiar with. And I'll bet for a lot of people *not changing the coin supply after genesis* is sacred. For me it's not — just extremely expensive to change. (And by the way I strongly object to the idea that changing that is theft. If you think the immutability of that is sacred, that's fine with me. It's your right to have your own moral beliefs, and I can see where you are coming from. But if you think that changing that is theft then you're just wrong.)

I think it might be worth trying to find a few things that we can all agree on before the end of the Constitutional Convention. I predict none of the above examples will qualify (I for one am currently unwilling to sign off on them) but I'd like to see it tried. An example of a sacred agreements that I think would succeed is a binding commitment to no-backdoors (I.e. transparency, fairness, and trustworthiness of the protocol and code) on the basis of human rights.

**Comment by zookozcash** [comment]
> 0.20 Donors to the Zcash Foundation
> 0.20 Miners (proportional by hashpower)
> 0.20 Current Zcash holders (proportional to value)
> 0.20 Board-chosen allocation of outside experts / “friends of the foundation”
> 0.20 Board-chosen allocation of contributors / developers

What about commercial enterprises? Do they fit in as "developers", alongside individual open-source volunteers?

Suppose some megacorporation, like one of the FAANGs, is considering launching a major strategic investment in Zcash. If they knew they would get representation on the Foundation that might encourage them to do so. But with this structure it looks like they get representation only inasmuch as the board might choose representative(s) for the last category that represent their interests.

How does the Zcash Company fit in? (Not yet a megacorporation.) Are we part of the Zcash Foundation or a thing apart? (Both options seem to have advantages.)

**Comment by zookozcash** [comment]
To explain more specifically what I meant about the Constitutional Convention answering the question of "What is sacred to everyone in this community?", I was basically imagining something akin to Constitutional Amendments, specifying something like "Regardless of any other bylaws or any decisions of the Board, the Zcash Foundation shall not XYZ". Of course that also brings into scope a need for a process of overturning such amendments and amending the Constitution.

**Comment by zookozcash** [comment]
This comment is about what I perceive to be an important, ongoing, and compounding problem. I think the governance structure needs to be designed with a cure for this problem in mind. But I'm not going to try to come up with any proposed solutions in this comment.

The problem is that the Zcash Foundation is a very USA-centric organization. It is governed by USA, 100% of [the current board](https://z.cash.foundation//about/) is USA-resident USA-citizens. I haven't checked, but my impression is that 100% of the first round of grant recipients were from USA or Europe, which I think is indicative of "Where have people heard about the existence of the Zcash Foundation?" (i.e. in what languages, places, and internet forums).

I think in the coming years and decades, outside-USA and even outside-{USA/Europe/Western/Anglophone} will have the biggest and most important constituencies for the Zcash Foundation's mission, and that it will be difficult for those constituencies to exercise power over The Zcash Foundation which is proportional to their level of ownership of and reliance on the Zcash technologies and economic networks. It will also be difficult for those constituencies to exercise real oversight over the Zcash Foundation, because transparency processes which give insight into the Zcash Foundation to USAsians and Europeans may be meaningless/inaccessible to these others.

To earn and gain trust _among those constituencies_ as a steward of the Zcash technologies and economic networks, as well as any other, broader missions is quite a challenge. It might be appropriate to try to bake some solution into the fundamental structure and constitution of The Zcash Foundation. It might also be appropriate to commit to _not_ doing this, focus the Zcash Foundation on serving the Western/anglophone world, and explicitly make space for other organizations to serve other populations.

**Comment by zookozcash** [comment]
Some private comments I've heard about this topic are interesting because they indicate to me that they conceive of the Zcash Foundation's _possible scope of action_ as limited in different specific ways. Interestingly, different people seem to have different assumptions from each other about what _possible actions_ the Zcash Foundation could do, but they each seem to be assuming that everyone else has the same idea they have about this.

I think this is fine fodder for the basic constitutional questions before us.

Here a few questions to get us started thinking about where the bounds of the Zcash Foundation's authority lie.

Could it ever be appropriate, and possible, and Good and Right, for the Zcash Foundation to:

 * Support a backwards-incompatible (so-called “hard forking”) network upgrade, such as [Overwinter and Sapling](https://z.cash/blog/roadmap-update-2017-12.html) that the Zcash Company is developing and deploying?
 * Oppose such a backwards-incompatible network upgrade that the Zcash Company is developing and deploying?
 * Develop and deploy its own backwards-incompatible network upgrade? What about one that might be opposed by The Zcash Company or by another powerful stakeholder? (See also [A Future Friendly Fork](https://z.cash/blog/future-friendly-fork.html).)
 * Support an upgrade that changes the 21M total supply cap?
 * Support an upgrade that changes the Proof-of-Work algorithm?
 * Support an upgrade that switches from Proof-of-Work to Proof-of-Stake?
 * Support an upgrade that changes the amount or recipients of the Founder's Reward?
 * Support an upgrade that changes the amount or recipients of the block reward? (For example, "50% of the block reward goes to the miner who found the block, and 50% of the block reward goes to some specific public keys selected by some specific process.")
 * Contribute improvements (for example, security audits, security fixes, performance and feature upgrades) to other coins such as Monero?
 * Develop their own complete Zcash implementation?
 * Develop their own complete Monero implementation?
 * Launch a new coin?
 * Launch a "fork"/"airdrop", such as by forking the Zcash blockchain or the Bitcoin blockchain or the Ethereum blockchain, and/or by giving all current holders of other coins free newly-generated coins?

Okay, if you can think of other similar suggestions of _possible actions_ that the Zcash Foundation could conceivably undertake and that different people might have different assumptions about whether that could ever be a reasonable course of action, please post them.

**Comment by ericmeltzer** [comment]
I'd like to chime in to address two points brought up earlier in the thread—Zooko's point that the Foundation is currently very USA centric, and also the question of what type of decisions the Foundation should be making. I'll start by noting that I think the foundation has done a wonderful job so far, and that **not changing it at all** should be seen as a totally viable choice. tl;dr on this is that I think the foundation should try and find some members representing the Asian community, but shouldn't enshrine any geographical diversity requirement into bylaw, and that the foundation should laser-focus on grantmaking over taking positions on larger issues in the Zcash space. 

**USA-centricity**
I agree that the foundation is currently very USA-centric, which I think is a reflection of the Zcash community as a whole. Notably this _isn't_ true of the cryptocurrency community at large, which includes a huge number of Japanese, Korean, and Chinese people. It will be important to grow awareness and adoption of Zcash in Asia over the next few years, and that's something I personally will be doing in a variety of ways. I don't think ensuring geographically diverse foundation membership is something that should be baked into any constitution, nor do I think it should be ignored or that the foundation should commit to just biting the bullet on being US-centric. Rather, I'd like to see the foundation gain some Asian representation organically (via whatever process, whether voting or nomination) as the Asian Zcash community itself grows. This is a point in favor of having some sort of turnover in the foundation board, in order that the foundation can be representative of the Zcash community makeup at any given time and not just be a frozen snapshot of its USA-centric beginnings. 

**What type of decisions does the foundation contribute to?**
A foundation is a peculiar kind of critter which only has two basic verbs available to it. It can **give** money to other entities, and it can **issue statements** on important matters in the community. Over the first year of its existence, the Foundation has focused on giving money in the form of grants, and I think that should continue to be its focus. For that reason I don't think it's particularly important to ensure that miners or corporate entities or even large Zcash holders (of which I am one, through our fund) have a huge say in Foundation grants, because that should mostly be left up to people with academic and/or engineering expertise in subjects relevant to building digital money systems! 

While the foundation is of course free to make statements and take positions on any of the issues mentioned in this thread (planned network upgrades etc) I think it's far more valuable as a dedicated funding source for research that will move Zcash forward, so governance buildout should keep that in mind. 

The existence of such an enormous funding pool for Zcash-adjacent research is _insanely_ exciting and mostly underappreciated by the crypto community at large. With its current endowment, the Zcash foundation is similar in scale to a medium-size academic funding agency, and so a focus on grantmaking to academics with existing expertise makes sense. This is naturally somewhat limited (in a convo I had with a group working on zk-STARK development, a member of the group convincingly made the case to me that there are around 50 people in the world who really could contribute to this work!)  As the endowment grows, however, the foundation may end up having enough money to start addressing this issue at multiple levels; for example, creating a training program for software developers who wish to transition into cryptography research or blockchain development!

The foundation will naturally take positions on developments in the Zcash ecosystem and that's awesome (as its another nexus of power in the distributed community that makes up Zcash) but putting too much thought into the Foundation's makeup with that in mind is a distraction its primary grantmaking function in my opinion.

**Comment by amiller** [comment]
Thanks all for this excellent conversation! Just to quickly react to one of ericmeltzer's points... 
 It's possible the foundation could issue statements in favor of some upgrade or another. If the foundation employs all the core developers, however, then perhaps this "statement" would have a unilateral effect and be something stronger. IMO we should make sure that's not the case.

 In my view, the foundation can do something else too. We can have programs to help conduct polls, deliberate in organized public ways, and solicit more input and voice from broad parts of the community. This thread already touches on some ways of doing that. The outcomes of such would only be binding to the extent the miners, node operators, wallet developers, etc consent, but that's the case anyway. The point is, this is something the foundation could do to help make decisions that *does not* require the foundation to take a side and advocate it.

**Comment by zookozcash** [comment]
Against voting, by @nayafia: https://medium.com/@nayafia/the-problem-with-voting-8cff39f771e8

**Comment by JMoVS** [comment]
Is there layout out somewhere what the admired result for this board is? Like what kind of questions it has to answer, and what kind of decisions it has to make in what timeframe and what environment? To properly model it, i think designated goals should be layout out first

**Comment by zmanian** [comment]
Here are my ideal qualities in a board of crypto currency foundation.

1. The Board Members should have independence. Board members should have substantial equities outside of their participation in the board. This makes board members more resistant to corrupting influences.

2. Board Members should have legitimacy. Board members should be perceived as accountable to the interests of Zcash community and privacy and security community in general.

3. Board Member should be aligned with the mission of the Foundation to realize the potential for private economic interactions on public blockchains.

**Comment by amiller** [comment]
Hi all, here is a further iteration of a proposed plan for our election. The proposed election has a limited scope, and the following concrete goals:

- Expand the Zcash Foundation Board to 7 seats
- Broaden the Foundation's governance process to include voices of the community
- Set up a voting structure for Board members — based on community input — that could be used for other proposals and decisions

https://github.com/amiller/ZcashFoundation/blob/election/election-proposal.md

Would love to hear more feedback on this. I'd also note that this is still a starting point, there are many good points mentioned in this thread that this proposal does not yet directly solve.

**Comment by amiller** [comment]
A few voting researchers I spoke to suggested that secret ballots is even *more* important in a relatively small community like ours. I'm partial to this observation. Another suggestion is that Helios https://vote.heliosvoting.org/ is already quite mature and would be something we could likely use, providing ballot secrecy and public verifiability (at least in the sense that individuals can verify their vote is included and can post their encrypted ballots publicly). I think this is probably a good idea for us. We'll look into it more.

**Comment by zmanian** [comment]
I think Helios is great. We will need some sort of registrar that the Foundation will operate to hand out accounts and some criteria for doing so.

Should the full registration list be public?

**Comment by amiller** [comment]
I think we (foundation board/staff) should propose and curate a public list very shortly (like in the next week or two at most) and let it settle / wait for consensus / let people object to biases etc. The Helios server seems to handle email sign-ups automatically so if we know an email address for each panel member can use that. Otherwise we can pass the signup token on to the panel member. In either case, we'd rely on the panel members to make use of public channels (github or twitter or whatever) to ensure their ballot is cast correctly.

**Comment by acityinohio** [comment]
@zmanian @amiller would a publicly readable google spreadsheet work for the list? I can start/administer that soon (realistically week of March 12th/after my Powers of Tau contribution) and get my feet wet with Helios then as well.

**Comment by amiller** [comment]
Closing this https://z.cash.foundation//blog/governance-results/
