### ISSUE TITLE
Working Group organization

### ISSUE THREAD

**Issue by amiller** [ZcashFoundation/ZcashFoundation#6]
Zcash Foundation will need to help instigate and coordinate the efforts of volunteers.
["Working Groups" ](https://en.wikipedia.org/wiki/Working_group) can be a lightweight structure for organizing groups of volunteers around projects or tasks.

This ticket is for discussing the possibility of working groups and how to organize them, or possibly alternatives.

The idea is that working groups should be mostly self-run, bottom up (from volunteers who want to do something) as opposed to top down (appointed by the board?). Working groups should be empowered to self-organize, set their own policies, etc., without needing to seek permission / micromanagement. However, they should be able to benefit from some consistency / convention / visibility from being included in the foundation.

Here are some ideas of potential working groups, based on projects already underway:
- Educating non profits on accepting private donations
- Education on SNARKs
- Setting up polling infrastructure to get input from miners #4 or other parts of the ecosystem
- Planning a Zcon conference
- Technical development

Some questions to answer in this discussion: what does it mean to be "official"? Does the foundation "own" the working group or have the right to disband it? Do working groups get funding?

Here's my proposal for how to do this in a minimalistic way. The Foundation could have a policy for officially "recognizing" a Working Group.
- The decision to recognize a working group would initially rest with the Foundation Board unless delegated
- Recognized working groups will be maintained in a list on the Foundation's webpage and github
- The Foundation will collect monthly (?) status updates from each working group, and publish them (or present them at a hangout of some kind)
- Each working group will have a coordinator, their contact information will be posted so potential volunteers can see a place to join up
- Working groups should have some kind of public communication infrastructure, either a mailing-list, forum (subcategory of the forum.z.cash?) or at least a channel on zcashcommunity chat.
- Working groups are expected to uphold the Foundation VALUES, possibly a code of conduct
- The Foundation can enforce this mainly by "withdrawing recognition". 

I like the "recognition" verbiage because it acknowledges that working groups are independent and could continue operating independently of the Foundation too.

As a light-weight process, there's not yet a policy for how working groups could receive funding from the Foundation, so by default that would have to be at the board's discretion separately.

**Comment by ioptio** [comment]
Is the idea to merge this with/take over https://github.com/zcash/zcash/wiki/working-groups or keep separate?

**Comment by nathan-at-least** [comment]
My vision is to migrate ZcashCo dev organization into this working group model, thus breaking development out of that company's walled garden. Getting there will be a process that takes time.

I think the next step for our company is to notice when we have a new company initiative that could fit in this working group mould, and then to do so rather than just setting up an internal team. I'm motivated to do this relatively soon even if the structure or understanding of working groups is in flux to serve a prototyping role.

**Comment by nathan-at-least** [comment]
The current policy lives here: https://github.com/ZcashFoundation/ZcashFoundation/blob/master/WorkingGroups/README.md

Is the existence of that README.md sufficient to close this ticket?

**Comment by amiller** [comment]
We can close it once at least one working group "grows up" in some way. We'll recognize this way when we see it (or we should work out what is the minimum "success" criteria for this issue in further comments)

**Comment by nathan-at-least** [comment]
I propose this criterion:

- The Foundation has published 2 monthly Zcash Foundation newsletters.
- Both newsletters have status updates from the same two or more working groups.

   + If working groups drop out or go idle on month two, this criterion fails because maybe we need to tweak something.
   + If there is some churn but at least two are stable, that's acceptable.

- The two-or-more working groups have to have had one meeting and some new status for both months.

This is intended to be easily measurable, achievable, and set a goal so that everyone knows what growing up is and that we have indeed grown up.

**Edit:** I say "newletter" but I don't care what format it is, except I strongly prefer something with a stable URL. Examples: A mailing list with a public archive website, a blog post, a wiki page (that isn't edited much after the fact).

**Comment by nathan-at-least** [comment]
I have a personal preference for "newletters" in the form of blog posts, or anything we can publicly link to with a stable URL. (I personally dislike signing up for email announcement lists because I'm already on too many and end up ignoring them all.)

**Comment by amiller** [comment]
I vote to call the working groups attempt a failure and garbage collect it, after which we can just close this issue.
Or if there's something to salvage, make a new issue for that.

**Comment by acityinohio** [comment]
Closing this out for now as part of ZcF GitHub Issues cleanup.
