### ISSUE TITLE
what you need to exercise your freedom in a decentralized cryptocurrency

### ISSUE THREAD

**Issue by zookozcash** [ZcashFoundation/ZcashFoundation#67]
I think there are three things you need to exercise your natural freedom in a decentralized cryptocurrency community. Currently the Foundation doesn't have any of the three. If you don't have "the ability to exercise your freedom", then if you and a group of community members want to share some technology/crypto-asset/network with each other, you have to ask someone else to please help you do it. And what if they don't do what you ask?

For example, what if a group of community members wants to have a variant of Zcash coins which are mined with a different Proof-of-Work than another group of community members want. You can tell that you don't have "the ability to exercise your freedom", because even after you've agreed with your group on what you all want to do together, then you can't actually do it until someone else does it for you.

The three things are:

1. The legal right to use the name "Zcash", the golden Z logo, and other potentially trademark-protectable things like the ZEC ticker symbol.

   Currently, the Zcash Co has legal ownership of those trademarks, and allows anyone in the world to use them under these terms: https://z.cash/trademark-policy.html

   Currently, a group of community members who wanted to do a certain thing together (e.g. use a certain PoW algorithm) might or might not be legally allowed to call their thing "Zcash", depending. (Of course that might be okay if you don't mind calling it by a different name.)

   Maybe we could arrange for the Foundation (or others) to have more legal rights to the trademarks.

2. Funding which is not dependent on anyone else's good graces.

   Currently the Zcash Foundation has certain funds in the bank, and under their exclusive control, but the future funding from the Zcash blockchain flows through the Zcash Company and then to certain founders (myself included), who have pledged to donate some of it to the Foundation every month until the end of the Founder's Reward. What if those founders threatened to cut off that flow of funds unless the Foundation did certain things or refrained from doing certain things?

   Maybe we could arrange for the Foundation's funding to instead come straight from the blockchain to the Foundation instead of passing through the company and certain founders along the way.

3. Software development chops.

   Currently the core implementation and the `zcashd` full node software are maintained almost entirely by the Zcash Company engineers. What if you and a group of like-minded community members want to run a variant of it with some differences, such as a different Proof-of-Work algorithm, than the one the Zcash Company maintains?

   I like to think of "Which software do I trust to tell me whether a certain payment is valid?" as the fundamental voting process. Voting A or B in a ballot (even if it is on a blockchain) doesn't feel like the _real_ vote to me — that's just everyone coordinating with one another about how they intend to cast their _real_ vote. The real vote is download A or B software and start trusting it to tell you which coins are valid and which coins aren't. But currently there's only one option available to download!

   Maybe the Zcash Foundation could develop the resources (internally, or through connections with other companies/organizations, or other open source developers) to provide an alternative download so that people can vote.

**Comment by zookozcash** [comment]
P.S. Also what if the company and the founders _wanted_ to keep delivering the pledged funds to the Foundation, but couldn't because of some problem like: we've been sued and the judge froze all of our assets pending the lawsuit, or we've been robbed and lost control of all of our private spending keys. Or a founder like me died. Or what if some third party who had the ability to sue, rob, or control the company or the founders then threatened the Zcash Foundation that they would use that power to cut off the Zcash Foundation's funds unless the Foundation did certain things or refrained from doing certain things?

**Comment by jasondavies** [comment]
> Maybe we could arrange for the Foundation's funding to instead come straight from the blockchain to the Foundation instead of passing through the company and certain founders along the way.

It seems like this could be easily achieved by modifying the reward function so that it pays the appropriate split between ZcashCo and the Foundation. Would require a hard fork (all nodes would need to be updated to validate the new rules).

**Comment by amiller** [comment]
Thanks for this. I agree with all the points basically. I think the foundation should do, in order:
1. Receive a transfer of trademarks to the company. I believe we have the staff and capacity to define and enforce a trademark policy in a reasonable way. I also think this is *mostly* symbolic, since I don't have strong thoughts on how else to treat the trademark policy than what the company is already doing. I'm planning to add a ballot option indicating our intent to receive those.
2. Our plans for the next year include building technical capacity. I think we should try to build an independent implementation and have an independent core development team.
3. Agree that we should hard fork at some point so that the FR pledged to the foundation is handled automatically in code rather than carried out by the company.

**Comment by tloriato** [comment]
I agree with each and every one of amiller's point. 

But I'd also like to raise the question if it would be possible to include the payout to the Foundation in the upcoming Sapling Hard Fork. I don't think that it would be very time-demanding given [those lines](https://github.com/zcash/zcash/blob/9e5398686c729b3ca8197a379cf4e532a01a9fa2/src/chainparams.cpp#L179-L235) but Zcash Co has to have the final say in this, which, ironically, reinforces Zooko's third point.

**Comment by hosseamin** [comment]
Recently i saw this trademark policy. https://z.cash/trademark-policy.html
@zookozcash you are totally correct. I very much like to see possibility for having multiple deployment of zcashd.

**Comment by mcelrath** [comment]
On (3) I'm afraid Zcash is in the same boat as bitcoind itself due to their shared history code.  The ideal way to achieve this would not be to write an example implementation, but to write a spec (as is done with e.g. IETF/W3C standards) and then have alternative implementations write to the spec. So, since Bitcoin itself can't escape having its consensus rules defined only in code despite multiple alternative implementations, Zcash is similarly stuck.

Also the complexity and cryptographic knowledge required to implement the ZKP pieces seriously restrict the set of people who could create a truly independent full-node implementation in the first place, even if the shared history with Bitcoin wasn't a problem.

At first I was thinking that it should be easy to get e.g. btcd/libbitcoin/bitcoinj/bcoin to implement the ZKP pieces, but this doesn't escape either of these problems. The zcash-developed code will still be "right" in the event of an unexpected code bug, just as it is with Bitcoin. The ZKP pieces would likely be copied directly (especially for C++ alternative implementations like libbitcoin) but this obviously doesn't evade the problem since bugs will be copied too, so this isn't truly an independent implementation.

If I was starting from scratch with a coin project and wanted to solve (3) I'd write a spec instead of a full node, and only go live when there were 2-3 independent implementations (Lightning Network is doing awesome in this regard, and is a model for the future -- but they don't need consensus). Hopefully as time goes on, such projects won't be so heavily dev-limited that one implementation is the only reasonable path. Wait a year or two for thousands of ICOs to crash and their devs to enter the job market...

**Comment by zookozcash** [comment]
There's a spec: https://github.com/zcash/zips/blob/master/protocol/protocol.pdf

**Comment by HershyatHatch** [comment]
For Zooko and/or Andrew - so, to your mind, would the decision to 'automate' the contribution to the foundation require a vote from the whole community or just the founders as it is the rights to their money that is being decided on?

**Comment by acityinohio** [comment]
Thanks for the discussion all, but closing this out now as part of ZcF GitHub Issues cleanup.
